name:                aoc
version:             2022.0
github:              "Jtag84/adventOfCodeHaskell"
license:             BSD3
author:              "Clement"
copyright:           "2022 Clement"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         2022 Advent of Code projects in Haskell

dependencies:
- ansi-terminal
- attoparsec
- base >= 4.7 && < 5
- containers
- directory
- intset
- matrix
- mtl
- optparse-applicative
- parallel
- parser-combinators
- safe
- scientific
- text
- time
- tuple
- vector

library:
  source-dirs: src
  default-extensions:
    - GADTs
    - GHC2021
    - LambdaCase
    - MultiWayIf
    - OverloadedRecordDot
    - OverloadedStrings
    - RecordWildCards

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -fexcess-precision
    - -funfolding-use-threshold=16
    - -O2
    - -optc-ffast-math
    - -optc-O3
    - -rtsopts
    - -threaded
    - -with-rtsopts=-C0
    - -with-rtsopts=-N4
    - -with-rtsopts=-qa
    default-extensions:
    - GADTs
    - GHC2021
    - LambdaCase
    - MultiWayIf
    - OverloadedRecordDot
    - OverloadedStrings
    - RecordWildCards
    dependencies:
    - aoc
